apiVersion: vault-secret.io/v1alpha1
kind: VaultSecret
metadata:
  name: example-vaultsecret
spec:
  serviceAccount: example-vaultsecret
  vaultAddress: vault.default:8200
  vaultAgent:
    autoAuthMethod: |
      method "kubernetes" {
          mount_path = "auth/kubernetes"
          config = {
              role = "example"
          }
      }

  consulTemplate:
    templates: |
      template {
        # These are the delimiters to use in the template. The default is "{{" and
        # "}}", but for some templates, it may be easier to use a different delimiter
        # that does not conflict with the output file itself.
        left_delimiter  = "[["
        right_delimiter = "]]"
        destination = "/etc/secrets/index.html"
        contents = <<EOH
        <html>
        <body>
        <p>Some secrets:</p>
        [[- with secret "secret/config" ]]
        <ul>
        <li><pre>username: [[ .Data.username ]]</pre></li>
        <li><pre>password: [[ .Data.password ]]</pre></li>
        </ul>
        [[ end ]]
        </body>
        </html>
        EOH
      }
  secret:
    name: exmaple-vaultsecret
    keys:
      - key: a
        file: /etc/secrets/index.html