apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-vaultsecret
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: SecretCreator
subjects:
  - kind: ServiceAccount
    name: example-vaultsecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: SecretCreator
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-vaultsecret
  namespace: default
