// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/vaultsecret/v1alpha1.VaultSecret":       schema_pkg_apis_vaultsecret_v1alpha1_VaultSecret(ref),
		"./pkg/apis/vaultsecret/v1alpha1.VaultSecretSpec":   schema_pkg_apis_vaultsecret_v1alpha1_VaultSecretSpec(ref),
		"./pkg/apis/vaultsecret/v1alpha1.VaultSecretStatus": schema_pkg_apis_vaultsecret_v1alpha1_VaultSecretStatus(ref),
	}
}

func schema_pkg_apis_vaultsecret_v1alpha1_VaultSecret(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VaultSecret is the Schema for the vaultsecrets API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/vaultsecret/v1alpha1.VaultSecretSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/vaultsecret/v1alpha1.VaultSecretStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/vaultsecret/v1alpha1.VaultSecretSpec", "./pkg/apis/vaultsecret/v1alpha1.VaultSecretStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_vaultsecret_v1alpha1_VaultSecretSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VaultSecretSpec defines the desired state of VaultSecret",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"serviceAccount": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"vaultAddress": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"vaultCA": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"vaultAgent": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/vaultsecret/v1alpha1.VaultAgentSpec"),
						},
					},
					"consulTemplate": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/vaultsecret/v1alpha1.ConsulTemplateSpec"),
						},
					},
					"secret": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/vaultsecret/v1alpha1.SecretSpec"),
						},
					},
					"initContainers": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "set",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "InitContainers to be used on the POD",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("k8s.io/api/core/v1.Container"),
									},
								},
							},
						},
					},
					"extraContainers": {
						VendorExtensible: spec.VendorExtensible{
							Extensions: spec.Extensions{
								"x-kubernetes-list-type": "set",
							},
						},
						SchemaProps: spec.SchemaProps{
							Description: "ExtraContainers to be used on the POD along side the main containers",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("k8s.io/api/core/v1.Container"),
									},
								},
							},
						},
					},
				},
				Required: []string{"vaultAddress", "vaultAgent", "consulTemplate", "secret"},
			},
		},
		Dependencies: []string{
			"./pkg/apis/vaultsecret/v1alpha1.ConsulTemplateSpec", "./pkg/apis/vaultsecret/v1alpha1.SecretSpec", "./pkg/apis/vaultsecret/v1alpha1.VaultAgentSpec", "k8s.io/api/core/v1.Container"},
	}
}

func schema_pkg_apis_vaultsecret_v1alpha1_VaultSecretStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "VaultSecretStatus defines the observed state of VaultSecret",
				Type:        []string{"object"},
			},
		},
	}
}
