name: Make
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Operator-SDK Action
      uses: xUnholy/operator-sdk-github-action@v1.0.0
      env:
        RELEASE_VERSION: v0.13.0
        CGO_ENABLED: 0
      with:
        image: "carlosjgp/vault-secret-operator-controller"
        tag: v0.1.0

    - name: Docker Build & Push for kubectl
      uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: "carlosjgp/vault-secret-operator-kubectl"
        tag: v1.16-v0.1.0
        dockerfile: kubectl/Dockerfile
        username: carlosjgp
        password: ${{ secrets.DOCKERHUB_PASSWORD }}